channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
  - pyg

dependencies:
  - python=3.10
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - wandb=0.19.6
  - rdkit
  - torchvision
  - pip
  - pip:
      - torch-scatter
      - torch-sparse
